export const data = [
  {
    id: 1,
    name: "Nathan James",
    totalAmount: 200,
    urgency: "moderate",
    category: "Category 1",
    collectedAmount: 160,
    remainingAmount: 40,
  },
  {
    id: 2,
    name: "Mike Ross",
    totalAmount: 300,
    urgency: "neutral",
    category: "Category 2",
    collectedAmount: 100,
    remainingAmount: 200,
  },
  {
    id: 3,
    name: "Harvey Specter",
    totalAmount: 1234,
    urgency: "critical",
    category: "Category 3",
    collectedAmount: 123,
    remainingAmount: 1123,
  },
  {
    id: 4,
    name: "Natasha Williams",
    totalAmount: 2000,
    urgency: "neutral",
    category: "Category 4",
    collectedAmount: 800,
    remainingAmount: 1200,
  },
  {
    id: 5,
    name: "Tony Brad",
    totalAmount: 2010,
    urgency: "moderate",
    category: "Category 5",
    collectedAmount: 1600,
    remainingAmount: 410,
  },
  {
    id: 6,
    name: "Jessica Pearson",
    totalAmount: 200,
    urgency: "critical",
    category: "Category 6",
    collectedAmount: 160,
    remainingAmount: 40,
  },
  {
    id: 7,
    name: "Max Pitson",
    totalAmount: 100,
    urgency: "critical",
    category: "Category 7",
    collectedAmount: 0,
    remainingAmount: 100,
  },
  {
    id: 8,
    name: "Donna Paulson",
    totalAmount: 560,
    urgency: "neutral",
    category: "Category 8",
    collectedAmount: 140,
    remainingAmount: 420,
  },
  {
    id: 9,
    name: "Louis Litt",
    totalAmount: 200,
    urgency: "moderate",
    category: "Category 9",
    collectedAmount: 160,
    remainingAmount: 40,
  },
];
